'use strict'

const names = {
  ar: 'العربية',
  'be-tarask': 'Taraškievica',
  br: 'Brezhoneg',
  ca: 'Català',
  cs: 'Česky',
  da: 'Dansk',
  de: 'Deutsch',
  el: 'Ελληνικά',
  en: 'English',
  es: 'Español',
  et: 'Eesti',
  fa: 'فارسی',
  fr: 'Français',
  he: 'עברית',
  hrx: 'Hunsrik',
  hu: 'Magyar',
  ia: 'Interlingua',
  is: 'Íslenska',
  it: 'Italiano',
  ja: '日本語',
  kab: 'Kabyle',
  ko: '한국어',
  mk: 'Македонски',
  ms: 'Bahasa Melayu',
  nb: 'Norsk Bokmål',
  nl: 'Nederlands, Vlaams',
  oc: 'Lenga d\'òc',
  pl: 'Polski',
  pms: 'Piemontèis',
  'pt-br': 'Português Brasileiro',
  ro: 'Română',
  ru: 'Русский',
  sc: 'Sardu',
  sk: 'Slovenčina',
  sr: 'Српски',
  sv: 'Svenska',
  ta: 'தமிழ்',
  th: 'ภาษาไทย',
  tlh: 'tlhIngan Hol',
  tr: 'Türkçe',
  uk: 'Українська',
  vi: 'Tiếng Việt',
  'zh-hans': '简体中文',
  'zh-hant': '正體中文'
}

const rtl = ['ar', 'fa', 'he', 'lki']

export default { names, rtl }
